language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install: pip install bashlex
# command to run tests
install: python setup.py install
script:
  - python tests/parser_testing.py -v
  - python tests/tagged_generator_tests.py -v
